import type { CategoryId, Locale, Market } from "./commerce";

const copy = {
  en: { browse: "Explore departments", shop: "Browse catalogue", search: "Search products", cart: "Cart", track: "Track order", homeTitle: "Objects worth choosing.", homeText: "Explore products across the MATA3 catalogue for your market.", departments: "Departments", selection: "Catalogue", products: "products", noProducts: "No published products for this market yet.", filters: "Filters", clear: "Clear", all: "All", priceLow: "Price: low to high", priceHigh: "Price: high to low", newest: "Name", add: "Add to cart", unavailable: "Availability awaiting confirmation", subtotal: "Product subtotal", checkout: "Checkout", back: "Continue browsing", empty: "Your cart is empty.", configure: "Delivery and payment options are not configured yet.", contact: "Contact", address: "Address", delivery: "Delivery", payment: "Payment", review: "Review", language: "Language", country: "Country", choose: "Continue", searchEmpty: "No matching products", results: "Search results", product: "Product", remove: "Remove", quantity: "Quantity" },
  ar: { browse: "استكشف الأقسام", shop: "تصفح المنتجات", search: "ابحث عن منتج", cart: "السلة", track: "تتبع الطلب", homeTitle: "منتجات تستحق الاختيار.", homeText: "تصفح منتجات مَتاع المتاحة في بلدك.", departments: "الأقسام", selection: "المنتجات", products: "منتج", noProducts: "لا توجد منتجات منشورة لهذا السوق بعد.", filters: "التصفية", clear: "مسح", all: "الكل", priceLow: "السعر: من الأقل", priceHigh: "السعر: من الأعلى", newest: "الاسم", add: "أضف للسلة", unavailable: "التوفر قيد التأكيد", subtotal: "إجمالي المنتجات", checkout: "إتمام الطلب", back: "متابعة التسوق", empty: "سلتك فارغة.", configure: "خيارات التوصيل والدفع غير مهيأة بعد.", contact: "بيانات التواصل", address: "العنوان", delivery: "التوصيل", payment: "الدفع", review: "المراجعة", language: "اللغة", country: "البلد", choose: "متابعة", searchEmpty: "لا توجد منتجات مطابقة", results: "نتائج البحث", product: "المنتج", remove: "حذف", quantity: "الكمية" },
  fr: { browse: "Explorer les rayons", shop: "Voir le catalogue", search: "Rechercher un produit", cart: "Panier", track: "Suivre une commande", homeTitle: "Des objets à choisir.", homeText: "Explorez les produits MATA3 disponibles dans votre pays.", departments: "Rayons", selection: "Catalogue", products: "produits", noProducts: "Aucun produit publié pour ce marché.", filters: "Filtres", clear: "Effacer", all: "Tout", priceLow: "Prix croissant", priceHigh: "Prix décroissant", newest: "Nom", add: "Ajouter au panier", unavailable: "Disponibilité à confirmer", subtotal: "Sous-total produits", checkout: "Commander", back: "Continuer les achats", empty: "Votre panier est vide.", configure: "Les options de livraison et de paiement ne sont pas encore configurées.", contact: "Contact", address: "Adresse", delivery: "Livraison", payment: "Paiement", review: "Récapitulatif", language: "Langue", country: "Pays", choose: "Continuer", searchEmpty: "Aucun produit correspondant", results: "Résultats", product: "Produit", remove: "Retirer", quantity: "Quantité" }
} as const;
const categoryCopy: Record<CategoryId, Record<Locale, string>> = {
  gaming: { en: "Gaming", ar: "الألعاب", fr: "Jeux vidéo" },
  "computer-accessories": { en: "Computer accessories", ar: "ملحقات الكمبيوتر", fr: "Accessoires informatiques" },
  "mens-fashion": { en: "Men's fashion", ar: "أزياء الرجال", fr: "Mode homme" },
  "womens-fashion": { en: "Women's fashion", ar: "أزياء النساء", fr: "Mode femme" },
  "womens-bags": { en: "Women's bags", ar: "حقائب النساء", fr: "Sacs femme" }
};
export function t(locale: Locale) { return copy[locale]; }
export function categoryName(category: CategoryId, locale: Locale) { return categoryCopy[category]?.[locale] ?? category; }
export function marketName(market: Market, locale: Locale) { return market === "eg" ? (locale === "ar" ? "مصر" : locale === "fr" ? "Égypte" : "Egypt") : (locale === "ar" ? "المغرب" : locale === "fr" ? "Maroc" : "Morocco"); }
