"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { formatMoney, type Locale, type Market, type Money } from "@/lib/commerce";
type OrderView = { reference: string; market: string; currency: "EGP" | "MAD"; status: string; paymentStatus: string; placedAt: string;
  customerName: string; address: { region: string; city: string; detailedAddress: string }; delivery: { label: string; amount: Money };
  payment: { label: string }; itemsSubtotal: Money; grandTotal: Money; lines: { kind: string; name: string; variantLabel?: string; quantity: number; unitPrice: Money; lineTotal: Money }[]; availableCustomerActions: string[] };
function Details({ order, market, locale, confirmation }: { order: OrderView; market: Market; locale: Locale; confirmation: boolean }) {
  const base = "/" + market + "/" + locale;
  return <div className="order-view"><p className="eyebrow">MATA3 / {confirmation ? "ORDER RECEIVED" : "ORDER STATUS"}</p><h1>{confirmation ? (locale === "ar" ? "تم استلام طلبك" : locale === "fr" ? "Commande reçue" : "Order received") : (locale === "ar" ? "حالة الطلب" : locale === "fr" ? "Statut de commande" : "Order status")}</h1>
    <p>{locale === "ar" ? "رقم الطلب" : locale === "fr" ? "Référence" : "Order reference"}: <strong>{order.reference}</strong></p>
    <p>{locale === "ar" ? "الحالة الحالية" : locale === "fr" ? "Statut actuel" : "Current status"}: <strong>{order.status}</strong></p>
    <p>{locale === "ar" ? "تاريخ الطلب" : locale === "fr" ? "Date de commande" : "Placed"}: {new Date(order.placedAt).toLocaleString(locale === "ar" ? "ar-EG" : locale === "fr" ? "fr-MA" : "en-US")}</p>
    <div className="order-actions"><button className="button outline" onClick={() => void navigator.clipboard.writeText(order.reference)}>{locale === "ar" ? "نسخ رقم الطلب" : locale === "fr" ? "Copier la référence" : "Copy order reference"}</button><Link className="button outline" href={base + "/track"}>{locale === "ar" ? "تتبع الطلب" : locale === "fr" ? "Suivre la commande" : "Track order"}</Link><Link className="button gold" href={base}>{locale === "ar" ? "متابعة التسوق" : locale === "fr" ? "Continuer les achats" : "Continue shopping"}</Link></div>
    <div className="summary-card"><h2>{locale === "ar" ? "ملخص الطلب" : locale === "fr" ? "Résumé de commande" : "Order summary"}</h2>{order.lines.map((line,index) => <p key={index}>{line.name}{line.variantLabel ? " · " + line.variantLabel : ""} × {line.quantity} — {formatMoney(line.lineTotal,locale)}</p>)}<p>{locale === "ar" ? "التوصيل" : locale === "fr" ? "Livraison" : "Delivery"}: {order.delivery.label} · {formatMoney(order.delivery.amount,locale)}</p><p>{locale === "ar" ? "طريقة الدفع" : locale === "fr" ? "Paiement" : "Payment"}: {order.payment.label} ({order.paymentStatus})</p><strong className="summary-amount">{formatMoney(order.grandTotal,locale)}</strong></div>
  </div>;
}
export function OrderConfirmation({ market, locale, reference, token }: { market: Market; locale: Locale; reference: string; token: string }) {
  const [order,setOrder]=useState<OrderView|null>(null),[done,setDone]=useState(false);
  useEffect(()=>{const controller=new AbortController();const capability = token || sessionStorage.getItem("mata3-confirm-" + reference) || "";void fetch("/api/orders/confirm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reference,token:capability}),signal:controller.signal}).then(async r=>r.ok?await r.json() as OrderView:null).then(value=>{if(!controller.signal.aborted){setOrder(value);setDone(true);}}).catch(()=>{if(!controller.signal.aborted)setDone(true);});return()=>controller.abort();},[reference,token]);
  return <main className="inner-page">{!done ? <div className="empty-state">…</div> : order ? <Details order={order} market={market} locale={locale} confirmation /> : <div className="empty-state">Confirmation unavailable.</div>}</main>;
}
export function GuestTracking({ market, locale }: { market: Market; locale: Locale }) {
  const [reference,setReference]=useState(""),[phone,setPhone]=useState(""),[order,setOrder]=useState<OrderView|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setLoading(true);setError("");setOrder(null);try{const response=await fetch("/api/orders/track",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reference,phone})});if(!response.ok)throw Error();setOrder(await response.json() as OrderView);}catch{setError(locale==="ar"?"تعذر العثور على الطلب بهذه البيانات.":locale==="fr"?"Commande introuvable avec ces informations.":"Unable to retrieve an order with those details.");}finally{setLoading(false);}};
  return <main className="narrow-page"><p className="eyebrow">MATA3 / {locale==="ar"?"تتبع الطلب":locale==="fr"?"Suivi":"TRACK ORDER"}</p><h1>{locale==="ar"?"تتبع الطلب":locale==="fr"?"Suivre une commande":"Track your order"}</h1><form className="stack-form" onSubmit={submit}><label>{locale==="ar"?"رقم الطلب":locale==="fr"?"Référence":"Order reference"}<input required value={reference} onChange={e=>setReference(e.target.value)} autoComplete="off" /></label><label>{locale==="ar"?"رقم الهاتف المستخدم في الطلب":locale==="fr"?"Téléphone de la commande":"Phone used for the order"}<input required type="tel" value={phone} onChange={e=>setPhone(e.target.value)} autoComplete="tel" /></label><button className="button gold" disabled={loading}>{loading?"…":locale==="ar"?"بحث":locale==="fr"?"Rechercher":"Find order"}</button></form>{error&&<p role="alert">{error}</p>}{order&&<Details order={order} market={market} locale={locale} confirmation={false}/>}</main>;
}
