"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { categories, type Locale, type Market } from "@/lib/commerce";
import { categoryName, marketName, t } from "@/lib/i18n";

export function Header({ market, locale }: { market: Market; locale: Locale }) {
  const path = usePathname(), router = useRouter(), base = `/${market}/${locale}`, c = t(locale);
  const [menu, setMenu] = useState(false), [nested, setNested] = useState(false), [q, setQ] = useState("");
  const change = (m: Market, l: Locale) => { const next = `/${m}/${l}`; localStorage.setItem("mata3-context", next); router.push(m === market ? path.replace(/^\/(eg|ma)\/(ar|en|fr)/, next) : next); setMenu(false); };
  useEffect(() => { setMenu(false); setNested(false); }, [path]);
  return <><div className="topbar"><span>مَتاع · THE MODERN ARAB MERCHANT</span><Link href={`${base}/track`}>{c.track}</Link></div><header className="site-header"><button className="icon-button mobile-only" aria-label="Open menu" aria-expanded={menu} onClick={() => setMenu(true)}>☰</button><Link className="brand" href={base}><img className="brand-symbol" src="/icon.png" alt="" /><span>مَتاع <strong>MATA3</strong></span></Link><nav className="desktop-nav" aria-label="Departments">{categories.map(cat => <Link key={cat} href={`${base}/category/${cat}`}>{categoryName(cat, locale)}</Link>)}</nav><div className="header-actions"><form className="header-search" action={`${base}/search`}><input name="q" value={q} onChange={e => setQ(e.target.value)} placeholder={c.search} aria-label={c.search} /><button aria-label={c.search}>⌕</button></form><Link href={`${base}/cart`} aria-label={c.cart} className="bag-link">♧ <span>{c.cart}</span></Link></div></header><div className="utility-bar"><label>{c.country} <select value={market} onChange={e => change(e.target.value as Market, locale === "fr" && e.target.value === "eg" ? "ar" : locale)}><option value="eg">{marketName("eg", locale)} · EGP</option><option value="ma">{marketName("ma", locale)} · MAD</option></select></label><label>{c.language} <select value={locale} onChange={e => change(market, e.target.value as Locale)}><option value="ar">العربية</option><option value="en">English</option>{market === "ma" && <option value="fr">Français</option>}</select></label><Link href={`${base}/account`}>{c.account}</Link></div>{menu && <div className="menu-backdrop" onClick={() => setMenu(false)}><aside className="mobile-menu" onClick={e => e.stopPropagation()}><div className="menu-head"><button onClick={() => setNested(false)}>{nested ? "←" : "MATA3"}</button><button aria-label="Close menu" onClick={() => setMenu(false)}>×</button></div>{nested ? <nav>{categories.map(cat => <Link key={cat} href={`${base}/category/${cat}`}>{categoryName(cat, locale)} <span>↗</span></Link>)}</nav> : <nav><button onClick={() => setNested(true)}>{c.departments}<span>→</span></button><Link href={`${base}/account`}>{c.account}</Link><Link href={`${base}/track`}>{c.track}</Link><Link href={`${base}/cart`}>{c.cart}</Link></nav>}<div className="menu-selects"><label>{c.country}<select value={market} onChange={e => change(e.target.value as Market, locale === "fr" && e.target.value === "eg" ? "ar" : locale)}><option value="eg">Egypt · EGP</option><option value="ma">Morocco · MAD</option></select></label><label>{c.language}<select value={locale} onChange={e => change(market, e.target.value as Locale)}><option value="ar">العربية</option><option value="en">English</option>{market === "ma" && <option value="fr">Français</option>}</select></label></div></aside></div>}</>;
}
